version: '1'

services:
  vsvdev-springboot-container:
    image: vsvdev-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/vsvdev-springboot-container
    ports:
      - "8080-8100:8080"
