apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsvdev-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vsvdev-springboot
  template:
    metadata:
      labels:
        app: vsvdev-springboot
    spec:
      containers:
        - name: springboot
          image: vsvdevuaco/vsvdev-docker-demo:vsvdev-docker-demo
          ports:
            - containerPort: 8888
          env:
            - name: PORT
              value: "8888"
---
apiVersion: v1
kind: Service
metadata:
  name: vsvdev-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: vsvdev-springboot
